### ISSUE TITLE
关于分支合并的建议

### ISSUE THREAD

**Issue by TaoChenyue** [zhiyiYo/PyQt-Fluent-Widgets#100]
继续自#99的想法讨论。

我发现我的想法已经有人完成了，[Qtpy](https://github.com/spyder-ide/qtpy.git)就是专门用来快速迁移qt仓库的。我觉得可以建一个QtPy分支。

**Comment by zhiyiYo** [comment]
duck 不必，不如继续维护多个分支，依赖包 PyQt-Frameless-Window 的各个分支的代码在 linux 系统下都不一样，换了 qtpy 感觉也意义不大

**Comment by TaoChenyue** [comment]
这个项目如果越来越大，工作量不是得翻4倍甚至更多😓。

**Comment by zhiyiYo** [comment]
git cherry-pick 会出手

**Comment by TaoChenyue** [comment]
彳亍

**Comment by zhiyiYo** [comment]
@TaoChenyue 
我加一个 qtpy 分支，你可以在这上面维护你的代码

**Comment by TaoChenyue** [comment]
> @TaoChenyue 我加一个 qtpy 分支，你可以在这上面维护你的代码

好的

**Comment by zhiyiYo** [comment]
有在 pyqt5 上面测试吗

**Comment by TaoChenyue** [comment]
默认的就是pyqt5 测试没什么问题，我同步一下。

**Comment by zhiyiYo** [comment]
你把 qtpy-frameless-window 的 Linux 和 Mac 端的代码移除掉了吗

**Comment by TaoChenyue** [comment]
> 你把 qtpy-frameless-window 的 Linux 和 Mac 端的代码移除掉了吗

昨晚删了又加回来了

**Comment by TaoChenyue** [comment]
develop分支里是最新的

**Comment by zhiyiYo** [comment]
我感觉你其实用的还是 pyqt5，就算指定了 --api pyside2，如果环境里面安装了 pyqt5，其实用的还是 pyqt5，我把 pyqt5卸载掉按运行 `python demo.py --api pyside2` 就会报错 `qtpy.QtBindingMissingModuleError: The sip module was not found. It is not currently implemented in PySide2.`

**Comment by TaoChenyue** [comment]
对，我下午发现了这个问题。原因是qtpy第一次导入后环境变量就不会再改了。我单独分了个qt_api模块出来解决了这个问题。

**Comment by TaoChenyue** [comment]
你试试最新的QtPy-Frameless-Window

**Comment by TaoChenyue** [comment]
0.0.3版本

**Comment by zhiyiYo** [comment]
我记的得用户手动在主程序前面加一条 `from PySide6.QtCore import Qt` 才行

**Comment by TaoChenyue** [comment]
不用，在第一次导入qtpy前，设置好环境变量QT_API，那以后的qtpy就只使用对应的QT_API了。

**Comment by zhiyiYo** [comment]
> 0.0.3版本

这个版本支持 linux 吗

**Comment by TaoChenyue** [comment]
> 我记的得用户手动在主程序前面加一条 `from PySide6.QtCore import Qt` 才行


试试这个
```python
from qt_api import set_qt_api
set_qt_api(parse=True)
from qtpy.QtWidgets import QApplication
from qtframelesswindow import FramelessWindow

class Window(FramelessWindow):
    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self.setWindowTitle("QtPy-Frameless-Window")

if __name__ == "__main__":
    app = QApplication([])
    demo = Window()
    demo.show()
    app.exec_()
```

**Comment by zhiyiYo** [comment]
`app.exec_()` 在 PyQt6 下面应该会报错

**Comment by zhiyiYo** [comment]
```python
/home/zhiyiyo/.local/lib/python3.8/site-packages/qtpy/__init__.py:267: PythonQtWarning: Selected binding 'pyqt5' could not be found; falling back to 'pyside2'
  warnings.warn(
Using  PySide2
Traceback (most recent call last):
  File "demo.py", line 4, in <module>
    from qtframelesswindow import FramelessWindow
  File "/home/zhiyiyo/.local/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/zhiyiyo/Documents/Python_Study/QtPy-Frameless-Window/qtframelesswindow/__init__.py", line 3, in <module>
    from .titlebar import TitleBar, TitleBarButton, SvgTitleBarButton, StandardTitleBar
  File "/home/zhiyiyo/.local/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/zhiyiyo/Documents/Python_Study/QtPy-Frameless-Window/qtframelesswindow/titlebar/__init__.py", line 8, in <module>
    from ..utils import startSystemMove
  File "/home/zhiyiyo/.local/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/zhiyiyo/Documents/Python_Study/QtPy-Frameless-Window/qtframelesswindow/utils/__init__.py", line 9, in <module>
    from .linux_utils import LinuxMoveResize as MoveResize
  File "/home/zhiyiyo/.local/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)

```

**Comment by TaoChenyue** [comment]
版本多少，代码是啥。

**Comment by zhiyiYo** [comment]
用的 linux，windows 测试意义不大，因为各个分支在 Windows 上面代码几乎一样

**Comment by TaoChenyue** [comment]
刚发了0.0.4版本，把linux和mac放进去了，再试一下吧。

**Comment by zhiyiYo** [comment]
github 代码好像没变？

**Comment by TaoChenyue** [comment]
develop分支？

**Comment by TaoChenyue** [comment]
哦 demo确实没变，我在test里测试的，我改下。

**Comment by TaoChenyue** [comment]
好了

**Comment by zhiyiYo** [comment]
qtpy 的源代码
```python
"""Provides access to sip."""

from . import (
    PYQT5,
    PYQT6,
    PYSIDE2,
    PYSIDE6,
    QtBindingMissingModuleError,
)

if PYQT5:
    from PyQt5.sip import *
elif PYQT6:
    from PyQt6.sip import *
elif PYSIDE2:
    raise QtBindingMissingModuleError(name='sip')
elif PYSIDE6:
    raise QtBindingMissingModuleError(name='sip')
```

**Comment by TaoChenyue** [comment]
--api 还是指定不了环境吗

**Comment by TaoChenyue** [comment]
![image](https://user-images.githubusercontent.com/40346985/230907280-b3ef658b-27d4-438d-99b0-63bcccd5814b.png)
PySide依赖树没有sip啊

**Comment by zhiyiYo** [comment]
你在 linux_utils.py 里面导入了 sip 模块，所以引发了这个错误

**Comment by zhiyiYo** [comment]
之前不是说了吗，linux 端的无边框窗口实现代码不一样，不能直接用 qtpy，不过也许可以用环境变量判断一下当前使用的包是哪个

**Comment by TaoChenyue** [comment]
可以，FramelessWindow是昨天测试的，那时候我还没发现api没变过来的bug。我改改。

**Comment by TaoChenyue** [comment]
现在用了最简单直接的办法，linux和mac我直接原来的不同代码放在4个判断环境的if下了。等有测试条件了我再整整兼容写法。
