### ISSUE TITLE
[Bug]: Pyside2 版本经过 Nuikta 编译之后 ComboBox 下拉框抛出 TypeError

### ISSUE THREAD

**Issue by CheshireCC** [zhiyiYo/PyQt-Fluent-Widgets#1009]
### What happened?

Nuitka：2.4.11

开发环境下正常运行，当 Nuitka 编译之后，点击下拉框展开选项时连续抛出：

```
TypeError: _onValueChanged() takes 1 positional argument but 2 were given
TypeError: _updateMenuViewport() takes 1 positional argument but 2 were given
TypeError: _onValueChanged() takes 1 positional argument but 2 were given
TypeError: _updateMenuViewport() takes 1 positional argument but 2 were given
TypeError: _onValueChanged() takes 1 positional argument but 2 were given
TypeError: _updateMenuViewport() takes 1 positional argument but 2 were given
TypeError: _onValueChanged() takes 1 positional argument but 2 were given
TypeError: _updateMenuViewport() takes 1 positional argument but 2 were given
TypeError: _onValueChanged() takes 1 positional argument but 2 were given
TypeError: _updateMenuViewport() takes 1 positional argument but 2 were given
TypeError: _onValueChanged() takes 1 positional argument but 2 were given
TypeError: _updateMenuViewport() takes 1 positional argument but 2 were given
TypeError: _onValueChanged() takes 1 positional argument but 2 were given
TypeError: _updateMenuViewport() takes 1 positional argument but 2 were given
TypeError: _onValueChanged() takes 1 positional argument but 2 were given
TypeError: _updateMenuViewport() takes 1 positional argument but 2 were given
TypeError: _onValueChanged() takes 1 positional argument but 2 were given
TypeError: _updateMenuViewport() takes 1 positional argument but 2 were given
TypeError: _onValueChanged() takes 1 positional argument but 2 were given
TypeError: _updateMenuViewport() takes 1 positional argument but 2 were given
TypeError: _onValueChanged() takes 1 positional argument but 2 were given
TypeError: _updateMenuViewport() takes 1 positional argument but 2 were given
TypeError: _onValueChanged() takes 1 positional argument but 2 were given
TypeError: _updateMenuViewport() takes 1 positional argument but 2 were given
TypeError: _onValueChanged() takes 1 positional argument but 2 were given
TypeError: _updateMenuViewport() takes 1 positional argument but 2 were given
TypeError: _onValueChanged() takes 1 positional argument but 2 were given
TypeError: _updateMenuViewport() takes 1 positional argument but 2 were given
TypeError: _onValueChanged() takes 1 positional argument but 2 were given
TypeError: _updateMenuViewport() takes 1 positional argument but 2 were given
TypeError: _onValueChanged() takes 1 positional argument but 2 were given
TypeError: _updateMenuViewport() takes 1 positional argument but 2 were given
TypeError: _onValueChanged() takes 1 positional argument but 2 were given
TypeError: _updateMenuViewport() takes 1 positional argument but 2 were given
TypeError: deregister() missing 1 required positional argument: 'widget'
```

不清楚是否 Nuitka 版本过高？

### Operation System

Windows7 Sp1 （VM）

### Python Version

python 3.8.20 （Conda）

### PyQt/PySide Version

PySide2 5.15.2.1

### PyQt/PySide-Fluent-Widgets Version

pyside2-fluent-widgets v1.7.1

### How to Reproduce?

[test_combobox_nuitka.dist.zip](https://github.com/user-attachments/files/17690109/test_combobox_nuitka.dist.zip)
 后缀名改成 7Z

### Minimum code

```python3
from qframelesswindow import FramelessWindow
from qfluentwidgets import PushButton, ComboBox

from PySide2.QtCore import Qt
from PySide2.QtWidgets import QWidget, QVBoxLayout, QHBoxLayout,QLabel
from PySide2.QtWidgets import QApplication
import sys

class DXF_UI(FramelessWindow):


    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("读取文件")
        # self.setWindowIcon("icon.ico")
        self.resize(800, 600) 
        # self.central_widget = self.centralWidget()

        self.setupUI()
        # print(type(layouts))
        # self.comboBox_layout.addItems(layouts)
    
        self.comboBox_layout.addItem("0")
        self.comboBox_layout.addItem("1")
        self.comboBox_layout.addItem("2")
        self.comboBox_layout.addItem("3")
        
        self.signalsProcess()

    def signalsProcess(self):
        self.pushButton_layout.clicked.connect(self.getEntityFromLayer)

    def getEntityFromLayer(self):
        self.close()

    def setupUI(self):
        self.mainWidget = QWidget(self)
        self.mainWidget.setObjectName("mainWidget")
        self.mainLayout = QVBoxLayout(self.mainWidget)

        self.setLayout(self.mainLayout)

        self.mainLayout.addSpacing(50)

        self.HLayout_layout = QHBoxLayout()
        self.mainLayout.addLayout(self.HLayout_layout)

        self.label_layout = QLabel(self)
        self.label_layout.setText("选择图层：")
        self.HLayout_layout.addWidget(self.label_layout)
        self.comboBox_layout = ComboBox(self)        
        self.HLayout_layout.addWidget(self.comboBox_layout)
        self.pushButton_layout = PushButton(self)
        self.pushButton_layout.setText("读取当前图层")
        self.HLayout_layout.addWidget(self.pushButton_layout)
        self.HLayout_layout.setAlignment(Qt.AlignmentFlag.AlignLeft)

        self.HLayout_layout.setStretch(0, 1)
        self.HLayout_layout.setStretch(1, 5)
        self.HLayout_layout.setStretch(2, 1)

        self.mainLayout.setAlignment(Qt.AlignmentFlag.AlignTop)


if __name__ == "__main__":
    # 启动一个Qt程序，并使用传入的系统参数
    app = QApplication()
    # 实例化窗体
    mainWindows = DXF_UI()
    # 显示窗体
    mainWindows.show()
    # 退出程序，并使用app实例的退出代码
    sys.exit(app.exec_())

```
```

**Comment by CheshireCC** [comment]
另外如果添加过 TitleBar 的话还会出现最大化按钮失效：
```
RuntimeError: Internal C++ object (TitleBar) already deleted.
```

**Comment by zhiyiYo** [comment]
Nuitka 1.8.6 会不会报错

**Comment by CheshireCC** [comment]
> Nuitka 1.8.6 会不会报错

1.8.6 同样抛出异常

**Comment by CheshireCC** [comment]
如果把 ComboBox 换成 QComboBox 的话就不会抛出这个异常了欸

**Comment by zhiyiYo** [comment]
在这边加上 value 参数之后还会报错吗：
<img width="872" alt="image" src="https://github.com/user-attachments/assets/02f4e64d-0efa-454a-9993-6be6d58f2708">

**Comment by CheshireCC** [comment]
全部加上之后倒是不报上面的错了，但是报了新的错

```

[1;33m📢 Tips:[0m QFluentWidgets Pro is now released. Click [1;96mhttps://qfluentwidgets.com/pages/pro[0m to learn more about it.

Traceback (most recent call last):
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 879, in _onValueChanged
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 821, in _menuSize
AttributeError: 'NoneType' object has no attribute 'contentsMargins'
Traceback (most recent call last):
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 806, in _updateMenuViewport
AttributeError: 'MenuActionListWidget' object has no attribute 'view'
Traceback (most recent call last):
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 879, in _onValueChanged
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 821, in _menuSize
AttributeError: 'NoneType' object has no attribute 'contentsMargins'
Traceback (most recent call last):
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 806, in _updateMenuViewport
AttributeError: 'MenuActionListWidget' object has no attribute 'view'
Traceback (most recent call last):
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 879, in _onValueChanged
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 821, in _menuSize
AttributeError: 'NoneType' object has no attribute 'contentsMargins'
Traceback (most recent call last):
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 806, in _updateMenuViewport
AttributeError: 'MenuActionListWidget' object has no attribute 'view'
Traceback (most recent call last):
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 879, in _onValueChanged
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 821, in _menuSize
AttributeError: 'NoneType' object has no attribute 'contentsMargins'
Traceback (most recent call last):
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 806, in _updateMenuViewport
AttributeError: 'MenuActionListWidget' object has no attribute 'view'
Traceback (most recent call last):
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 879, in _onValueChanged
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 821, in _menuSize
AttributeError: 'NoneType' object has no attribute 'contentsMargins'
Traceback (most recent call last):
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 806, in _updateMenuViewport
AttributeError: 'MenuActionListWidget' object has no attribute 'view'
Traceback (most recent call last):
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 879, in _onValueChanged
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 821, in _menuSize
AttributeError: 'NoneType' object has no attribute 'contentsMargins'
Traceback (most recent call last):
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 806, in _updateMenuViewport
AttributeError: 'MenuActionListWidget' object has no attribute 'view'
Traceback (most recent call last):
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 879, in _onValueChanged
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 821, in _menuSize
AttributeError: 'NoneType' object has no attribute 'contentsMargins'
Traceback (most recent call last):
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 806, in _updateMenuViewport
AttributeError: 'MenuActionListWidget' object has no attribute 'view'
Traceback (most recent call last):
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 879, in _onValueChanged
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 821, in _menuSize
AttributeError: 'NoneType' object has no attribute 'contentsMargins'
Traceback (most recent call last):
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 806, in _updateMenuViewport
AttributeError: 'MenuActionListWidget' object has no attribute 'view'
Traceback (most recent call last):
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 879, in _onValueChanged
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 821, in _menuSize
AttributeError: 'NoneType' object has no attribute 'contentsMargins'
Traceback (most recent call last):
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 806, in _updateMenuViewport
AttributeError: 'MenuActionListWidget' object has no attribute 'view'
Traceback (most recent call last):
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 879, in _onValueChanged
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 821, in _menuSize
AttributeError: 'NoneType' object has no attribute 'contentsMargins'
Traceback (most recent call last):
  File "C:\Users\Cheshire\Desktop\PRDBMT\WIN_BU~2\TEST_C~1.DIS\qfluentwidgets\components\widgets\menu.py", line 806, in _updateMenuViewport
AttributeError: 'MenuActionListWidget' object has no attribute 'view'
TypeError: deregister() missing 1 required positional argument: 'widget'
```

**Comment by zhiyiYo** [comment]
nuitka 对 pyside2 的支持有限，不如换成 pyside6 6.1.2 ，同样支持 win7，就是不能用 webengine

**Comment by CheshireCC** [comment]
因为 pyside6 在 就系统环境下太难配置了所以我换成了 pyside2，我马上换成 pyside6.1.2 试试看❤️💕
