### ISSUE TITLE
MessageBox.show() not work

### ISSUE THREAD

**Issue by StoneMoe** [zhiyiYo/PyQt-Fluent-Widgets#103]
**Describe the bug**
Simply `MessageBox().show()` not work

**Environment**
- OS: Windows 11
- DPI scaling: 100%
- Python: 3.10.1 64bit
- PySide6==6.5.0
- PySide6-Fluent-Widgets==0.6.7

**To Reproduce**
Steps to reproduce the behavior(you can use gif to demonstrate the problem):
1. run the code below
2. click button
3. error occurred

**Code**
```python
#!/usr/bin/env python3
from PySide6.QtWidgets import QApplication, QHBoxLayout
from qfluentwidgets import MessageBox, PushButton
from qframelesswindow import FramelessWindow


class Window(FramelessWindow):
    def __init__(self):
        super().__init__()

        self.layout = QHBoxLayout(self)
        self.btn = PushButton('test', self)
        self.btn.clicked.connect(self.btn_clicked)
        self.layout.addWidget(self.btn)

    def btn_clicked(self):
        MessageBox('title', 'text', self).show()


if __name__ == '__main__':
    app = QApplication()
    w = Window()
    w.show()

    app.exec()


```

**Error**
when button clicked, no messagebox shown up and error occurred
```
Traceback (most recent call last):
  File "C:\Users\StoneMoe\Downloads\ai_sub\test.py", line 17, in btn_clicked
    MessageBox('title', 'text', self).show()
  File "C:\Users\StoneMoe\Downloads\ai_sub\venv\lib\site-packages\qfluentwidgets\components\dialog_box\dialog.py", line 131, in __init__
    super().__init__(parent=parent)
  File "C:\Users\StoneMoe\Downloads\ai_sub\venv\lib\site-packages\qfluentwidgets\components\dialog_box\mask_dialog_base.py", line 14, in __init__
    super().__init__(parent=parent)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

```

**Comment by zhiyiYo** [comment]
可能是pyside版本过高，试下6.4.2

**Comment by StoneMoe** [comment]
> 可能是pyside版本过高，试下6.4.2

`PySide6==6.4.2` 在复现例子中正常运行了。
但是Pyside6这个版本依赖的`shiboken==6.4.2`会导致其他库报错

**Comment by zhiyiYo** [comment]
pyside6 一堆奇奇怪怪的问题，心累
