### ISSUE TITLE
PySide6分支 gallery演示程序”带遮罩的对话框“组件运行报错

### ISSUE THREAD

**Issue by kimoziiiii** [zhiyiYo/PyQt-Fluent-Widgets#114]
**Describe the bug**
组件名：带遮罩的对话框
报错信息：
```
Traceback (most recent call last):
  File "d:\PySide6-Fluent-Scaffold\examples\gallery\app\view\dialog_interface.py", line 64, in showMessageDialog
    w = MessageBox(title, content, self.window())
  File "D:\PySide6-Fluent-Scaffold\.venv\lib\site-packages\qfluentwidgets\components\dialog_box\dialog.py", line 131, in __init__
    super().__init__(parent=parent)
  File "D:\PySide6-Fluent-Scaffold\.venv\lib\site-packages\qfluentwidgets\components\dialog_box\mask_dialog_base.py", line 21, in __init__
    self._hBoxLayout = QHBoxLayout(self)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

**Environment**
- OS: Windows 11
- DPI scaling: 150%
- Python: 3.10.10
- PySide: 6
- PyQt-Fluent-Widgets: 0.6.10

**To Reproduce**
Steps to reproduce the behavior(you can use gif to demonstrate the problem):
1. 进入对话框组件
2. 点击”带遮罩的对话框“按钮
4. 控制台报错

**Comment by zhiyiYo** [comment]
换成 6.4.2 试试，最近 6.5.0 好像问题挺多的
