### ISSUE TITLE
滚动平滑滚动区域会出现错误

### ISSUE THREAD

**Issue by quantumDCS** [zhiyiYo/PyQt-Fluent-Widgets#127]
**描述**
滚动一些平滑滚动区域时会出现异常，包括gallery示例中的”使用动画的平滑滚动区域"、example中的scroll_area示例、刚加入的时间选择器

**环境**
- OS:Windows 11
- DPI scaling: 150%
- Python: 3.11.3 64 Bit
- PyQt: 5.15.9
- PyQt-Fluent-Widgets: 0.7.0

**复现**
1.点击源码附带的gallery中的时间选择器
<img width="720" alt="image" src="https://user-images.githubusercontent.com/52899871/232267855-a2160529-bc4a-4fe0-bf1e-55eb1747aeb3.png">
2.使用鼠标滚轮滚动小时区域或者分钟区域
3.程序出现错误
4.跟0.7.0版本一同发布的打包好的gallery运行时没有发现此问题
**报错**
```
Traceback (most recent call last):
  File "C:\Users\###\AppData\Local\Programs\Python\Python311\Lib\site-packages\qfluentwidgets\components\widgets\scroll_area.py", line 151, in wheelEvent
    self.vScrollBar.scrollValue(-e.angleDelta().y())
  File "C:\Users\###\AppData\Local\Programs\Python\Python311\Lib\site-packages\qfluentwidgets\components\widgets\scroll_area.py", line 77, in scrollValue
    self.setValue(self.__value)
  File "C:\Users\###\AppData\Local\Programs\Python\Python311\Lib\site-packages\qfluentwidgets\components\widgets\scroll_area.py", line 64, in setValue
    self.ani.setDuration(self.duration * dv / 70)
TypeError: setDuration(self, msecs: int): argument 1 has unexpected type 'float'
```

**Comment by zhiyiYo** [comment]
感谢反馈，应该是 Python3.11 的原因，目前已修复此问题

**Comment by quantumDCS** [comment]
感谢，此问题已经解决。
