### ISSUE TITLE
pyside6版本里边的example里边的message_dialog样例运行报错。 

### ISSUE THREAD

**Issue by bbg221** [zhiyiYo/PyQt-Fluent-Widgets#185]
Traceback (most recent call last):
  File "D:\download\PyQt-Fluent-Widgets-PySide6\examples\message_dialog\demo.py", line 24, in showDialog
    w = MessageBox(title, content, self)
  File "C:\Users\桥南\AppData\Local\Programs\Python\Python310\lib\site-packages\qfluentwidgets\components\dialog_box\dialog.py", line 134, in __init__
    super().__init__(parent=parent)
  File "C:\Users\桥南\AppData\Local\Programs\Python\Python310\lib\site-packages\qfluentwidgets\components\dialog_box\mask_dialog_base.py", line 14, in __init__
    super().__init__(parent=parent)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

**Comment by zhiyiYo** [comment]
和 #122 重复了
