### ISSUE TITLE
Ui_MessageBox 初始化参数个数不足导致子类对象无法初始化

### ISSUE THREAD

**Issue by LittleNyima** [zhiyiYo/PyQt-Fluent-Widgets#193]
**Describe the bug**
`qfluentwidgets.components.dialog_box.dialog.Ui_MessageBox` 初始化参数个数不足导致子类对象无法初始化
（但实际的报错位置是不对的，并不是 `mask_dialog_base` 的问题，应该是 `Ui_MessageBox` 的问题）

**Environment**
- OS: macOS 13.3.1 (a)
- DPI scaling: 100%
- Python: 3.8.13 [Clang 12.0.0 ] :: Anaconda, Inc. on darwin
- PySide6: [e.g. 6.15.0]
- PyQt-Fluent-Widgets: [e.g 0.8.4]

**To Reproduce**
Steps to reproduce the behavior(you can use gif to demonstrate the problem):
在 gallery demo 中，点击左下角的头像按钮后，无法弹出对话框，同时后台报错：
```python
Traceback (most recent call last):
  File "/Users/littlenyima/code/PyQt-Fluent-Widgets/examples/gallery/app/view/main_window.py", line 199, in showMessageBox
    w = MessageBox(
  File "/opt/homebrew/anaconda3/envs/py38/lib/python3.8/site-packages/qfluentwidgets/components/dialog_box/dialog.py", line 134, in __init__
    super().__init__(parent=parent)
  File "/opt/homebrew/anaconda3/envs/py38/lib/python3.8/site-packages/qfluentwidgets/components/dialog_box/mask_dialog_base.py", line 14, in __init__
    super().__init__(parent=parent)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

**Code**
```python
# Minimum code to reproduce the error
from PySide6.QtWidgets import QApplication
from qfluentwidgets import MessageBox

app = QApplication()
w = MessageBox('title', 'content', None)
if w.exec():
    print(True)
```

**Expected behavior**
对话框应该正确弹出

**Screenshots**
![screenshot](https://s1.ax1x.com/2023/05/09/p90IIUA.png)

**Comment by zhiyiYo** [comment]
改成下面这样可以不？
```python
class Ui_MessageBox:
    """ Ui of message box """

    yesSignal = Signal()
    cancelSignal = Signal()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
```

**Comment by zhiyiYo** [comment]
建议使用 6.4.2，因为 pyside6.5.0 最大化后窗口会超出屏幕

**Comment by LittleNyima** [comment]
也可以，只要能解决初始化问题就行，pr 我也一起关了
