### ISSUE TITLE
在TextEdit、LineEdit右键，软件会闪退

### ISSUE THREAD

**Issue by qiye34** [zhiyiYo/PyQt-Fluent-Widgets#223]
**Describe the bug**
在TextEdit、LineEdit右键时，会闪退

**Environment**
- OS: Windows10
- DPI scaling: 100%
- Python: 3.10 64-bit
- PyQt: 5.15.9
- PyQt-Fluent-Widgets: 0.9.0

**Code**
```python
class LineEdit(QLineEdit):
    """ Line edit """

    def contextMenuEvent(self, e):
        menu = LineEditMenu(self)
        menu.exec_(e.globalPos())

class TextEdit(QTextEdit):
    """ Text edit """
    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self.scrollDelegate = SmoothScrollDelegate(self)
        FluentStyleSheet.LINE_EDIT.apply(self)
    def contextMenuEvent(self, e):
        menu = TextEditMenu(self)
        menu.exec_(e.globalPos())

Traceback (most recent call last):
  File "C:\Users\qiye\AppData\Local\Programs\Python\Python310\lib\site-packages\qfluentwidgets\components\widgets\line_edit.py", line 103, in contextMenuEvent
    menu.exec_(e.globalPos())
  File "C:\Users\qiye\AppData\Local\Programs\Python\Python310\lib\site-packages\qfluentwidgets\components\widgets\menu.py", line 612, in exec_
    self.exec(pos, ani, aniType)
TypeError: EditMenu.exec() takes from 2 to 3 positional arguments but 4 were given
```

**Screenshots**
![GIF 2023-5-22 22-51-29](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/62045842/69f747fd-9857-4d1e-adff-e85c5ad54994)

**Comment by zhiyiYo** [comment]
感谢反馈，目前已修复此问题
