### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by wu462** [zhiyiYo/PyQt-Fluent-Widgets#277]
Traceback (most recent call last):
  File "D:\conda\envs\seed\lib\site-packages\qfluentwidgets\components\widgets\scroll_bar.py", line 449, in mouseMoveEvent
    super().mouseMoveEvent(e)
  File "D:\conda\envs\seed\lib\site-packages\qfluentwidgets\components\widgets\scroll_bar.py", line 321, in mouseMoveEvent
    dv = int(dv / self._slideLength() * (self.maximum() - self.minimum()))
ZeroDivisionError: division by zero
    dv = int(dv / self._slideLength() * (self.maximum() - self.minimum()))
ZeroDivisionError: division by zero

**Comment by zhiyiYo** [comment]
改成下述代码可以正常工作吗：
```python
dv = int(dv / max(self._slideLength(), 1) * (self.maximum() - self.minimum()))
```

**Comment by wu462** [comment]
@zhiyiYo 可以正常工作，感谢🌹
