### ISSUE TITLE
在运行readme里面的gallery/demo.py报错

### ISSUE THREAD

**Issue by JingyuanBai** [zhiyiYo/PyQt-Fluent-Widgets#317]
Describe the bug
问题的简要描述。
在运行readme中的demo.py报错

Environment
环境信息

OS:  Windows10
Python: 3.8.8 64-bit
PyQt: 5.15.9
PyQt-Fluent-Widgets: 0.10.1
To Reproduce
复现问题的步骤，推荐使用 gif 进行演示。
Steps to reproduce the behavior(you can use gif to demonstrate the problem:)

运行python demo.py
报错信息如下：
Traceback (most recent call last):
  File "D:\Anaconda3\envs\py3.8\lib\site-packages\qfluentwidgets\components\widgets\acrylic_label.py", line 33, in run
    pixmap = gaussianBlur(
  File "D:\Anaconda3\envs\py3.8\lib\site-packages\qfluentwidgets\common\image_utils.py", line 18, in gaussianBlur
    image = Image.fromqpixmap(QPixmap(imagePath))
  File "D:\Anaconda3\envs\py3.8\lib\site-packages\PIL\Image.py", line 3112, in fromqpixmap
    raise ImportError(msg)
ImportError: Qt bindings are not installed

我看了下似乎与acrylic_label的图形解析有关，但是我单独运行./examples/acrylic_label下的demo.py并没有报错。
我参考了另一个人issue113尝试解决，发现解决不了，我的fluent-widgets没有下载错误。
![Snipaste_2023-07-02_01-50-33](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/102663151/3686d9f7-973d-4786-a361-d30e51d4f659)

**Comment by zhiyiYo** [comment]
建一个新的环境试试，实在不行就用轻量版的

**Comment by 3000ye** [comment]
把pillow库删掉就行了，原因是PIL库在更新后改为了pillow,所以会冲突。

**Comment by zhiyiYo** [comment]
把 pillow 版本换成 9.4.0 也行
