### ISSUE TITLE
Bug in PlainTextEdit

### ISSUE THREAD

**Issue by ImmiProgramer** [zhiyiYo/PyQt-Fluent-Widgets#328]
i face sometimes this error when i select some text in PlainTextEdit and press Right-click on mouse

(maybe this error show for show 'copy' icon in roundedMenu

Traceback (most recent call last):
  File "C:\Users\self\AppData\Local\Programs\Python\Python311\Lib\site-packages\qfluentwidgets\components\widgets\line_edit.py", line 308, in contextMenuEvent
    menu.exec_(e.globalPos())
  File "C:\Users\self\AppData\Local\Programs\Python\Python311\Lib\site-packages\qfluentwidgets\components\widgets\menu.py", line 666, in exec_
    self.exec(pos, ani, aniType)
  File "C:\Users\self\AppData\Local\Programs\Python\Python311\Lib\site-packages\qfluentwidgets\components\widgets\menu.py", line 946, in exec
    self.addAction([self.copyAct, self.selectAllAct])
  File "C:\Users\self\AppData\Local\Programs\Python\Python311\Lib\site-packages\qfluentwidgets\components\widgets\menu.py", line 330, in addAction
    item = self._createActionItem(action)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\self\AppData\Local\Programs\Python\Python311\Lib\site-packages\qfluentwidgets\components\widgets\menu.py", line 344, in _createActionItem
    item = QListWidgetItem(self._createItemIcon(action), action.text())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\self\AppData\Local\Programs\Python\Python311\Lib\site-packages\qfluentwidgets\components\widgets\menu.py", line 388, in _createItemIcon
    hasIcon = self._hasItemIcon()
              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\self\AppData\Local\Programs\Python\Python311\Lib\site-packages\qfluentwidgets\components\widgets\menu.py", line 357, in _hasItemIcon
    return any(not i.icon().isNull() for i in self._actions+self._subMenus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\self\AppData\Local\Programs\Python\Python311\Lib\site-packages\qfluentwidgets\components\widgets\menu.py", line 357, in <genexpr>
    return any(not i.icon().isNull() for i in self._actions+self._subMenus)
                   ^^^^^^
AttributeError: 'list' object has no attribute 'icon'

**Comment by ImmiProgramer** [comment]
def _hasItemIcon(self):
        return any(not i.icon().isNull() for i in self._actions+self._subMenus)

**Comment by zhiyiYo** [comment]
please provide the minimum code and the selected text in `PlainTextEdit`

**Comment by ImmiProgramer** [comment]
pte = PlainTextEdit()
        pte.appendPlainText('Business refers to an enter entity or organization that')
        pte.setReadOnly(True)
        self.mainLayout.addWidget(pte)

**Comment by zhiyiYo** [comment]
I can't reproduce this issue. Could you record a screen to demonstrate it?

**Comment by ImmiProgramer** [comment]
i face this issue sometimes
not always

**Comment by ImmiProgramer** [comment]
Now i face this issue:

QDragManager::drag in possibly invalid state
QPixmap::scaled: Pixmap is a null pixmap
QDragManager::drag in possibly invalid state
QDragManager::drag in possibly invalid state
QDragManager::drag in possibly invalid state

https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/eda9a7cd-d162-4323-b223-ee354c3ae346

**Comment by zhiyiYo** [comment]
> Now i face this issue:
> 
> QDragManager::drag in possibly invalid state QPixmap::scaled: Pixmap is a null pixmap QDragManager::drag in possibly invalid state QDragManager::drag in possibly invalid state QDragManager::drag in possibly invalid state
> 

I don't think this has anything to do with qfluentwidgets
