### ISSUE TITLE
Mac下在PlainTextEdit编辑框进行右键操作偶发崩溃

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#366]
目前只遇到一次，终端堆栈如下：
```shell
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qfluentwidgets/components/widgets/line_edit.py", line 308, in contextMenuEvent
    menu.exec_(e.globalPos())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qfluentwidgets/components/widgets/menu.py", line 666, in exec_
    self.exec(pos, ani, aniType)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qfluentwidgets/components/widgets/menu.py", line 946, in exec
    self.addAction([self.copyAct, self.selectAllAct])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qfluentwidgets/components/widgets/menu.py", line 330, in addAction
    item = self._createActionItem(action)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qfluentwidgets/components/widgets/menu.py", line 344, in _createActionItem
    item = QListWidgetItem(self._createItemIcon(action), action.text())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qfluentwidgets/components/widgets/menu.py", line 388, in _createItemIcon
    hasIcon = self._hasItemIcon()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qfluentwidgets/components/widgets/menu.py", line 357, in _hasItemIcon
    return any(not i.icon().isNull() for i in self._actions+self._subMenus)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qfluentwidgets/components/widgets/menu.py", line 357, in <genexpr>
    return any(not i.icon().isNull() for i in self._actions+self._subMenus)
AttributeError: 'list' object has no attribute 'icon'
```

**Comment by ImmiProgramer** [comment]
I also face that issue

https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/328

**Comment by LxHTT** [comment]
Windows同样遇到此问题

**Comment by LxHTT** [comment]
最新的1.0.4版本同样遇到此问题。经过排查，我发现这个问题在PlainTextEdit使用了setReadOnly(True)的情况下会出现，而不开启只读属性不存在此问题

**Comment by Justin62628** [comment]
Win下同样遇到了PlainTextEdit只读模式下偶尔崩溃的情况。无法稳定复现。

**Comment by zhiyiYo** [comment]
已修复此问题
