### ISSUE TITLE
Unable to see PyQt-Fluent-Widgets in QtDesigner

### ISSUE THREAD

**Issue by techieforgood** [zhiyiYo/PyQt-Fluent-Widgets#368]
Hi @zhiyiYo. First of all thanks a lot for creating this.

### System details

1. OS: 

```powershell
OsName                                                  : Microsoft Windows 10 Home Single Language
OsVersion                                               : 10.0.19045
```

2. Python:

  ```
  python --version
  Python 3.9.10
  ```
3. Shell: Powershell

### Commands

I ran the following commands:

1. Setup virtual environment with venv
```powershell
python -m venv pyqt5 --upgrade-deps
```

4. Activate virtual environment
```
pyqt5\Scripts\activate.ps1
```

5. Install `PyQt-Fluent-Widgets[full]`
```
pip install "PyQt-Fluent-Widgets[full]" -i https://pypi.org/simple/
```

<details><summary>Output</summary>
<p>

```
Looking in indexes: https://pypi.org/simple/
Collecting PyQt-Fluent-Widgets[full]
  Obtaining dependency information for PyQt-Fluent-Widgets[full] from https://files.pythonhosted.org/packages/27/6e/60fa397381dcd51a6a1c7b3345e1fe4c557c54c0867aae56c62a4279995f/PyQt_Fluent_Widgets-1.0.2-py3-none-any.whl.metadata
  Using cached PyQt_Fluent_Widgets-1.0.2-py3-none-any.whl.metadata (5.2 kB)
Collecting PyQt5>=5.15.0 (from PyQt-Fluent-Widgets[full])
  Using cached PyQt5-5.15.9-cp37-abi3-win_amd64.whl (6.8 MB)
Collecting PyQt5-Frameless-Window>=0.2.7 (from PyQt-Fluent-Widgets[full])
  Obtaining dependency information for PyQt5-Frameless-Window>=0.2.7 from https://files.pythonhosted.org/packages/aa/22/11220b8a6f32d4e6c322d333231b5a0d58972efb6244f29d34fd2924d24b/PyQt5_Frameless_Window-0.2.8-py3-none-any.whl.metadata
  Using cached PyQt5_Frameless_Window-0.2.8-py3-none-any.whl.metadata (5.4 kB)
Collecting darkdetect (from PyQt-Fluent-Widgets[full])
  Using cached darkdetect-0.8.0-py3-none-any.whl (9.0 kB)
Collecting scipy (from PyQt-Fluent-Widgets[full])
  Obtaining dependency information for scipy from https://files.pythonhosted.org/packages/96/9b/10048be0c335327077af430c5a6637c0b9e7fe9121a8048836f1bb022a81/scipy-1.11.1-cp39-cp39-win_amd64.whl.metadata
  Using cached scipy-1.11.1-cp39-cp39-win_amd64.whl.metadata (59 kB)
Collecting pillow (from PyQt-Fluent-Widgets[full])
  Obtaining dependency information for pillow from https://files.pythonhosted.org/packages/8f/b8/1bf1012eee3059d150194d1fab148f553f3df42cf412e4e6656c772afad9/Pillow-10.0.0-cp39-cp39-win_amd64.whl.metadata
  Using cached Pillow-10.0.0-cp39-cp39-win_amd64.whl.metadata (9.6 kB)
Collecting colorthief (from PyQt-Fluent-Widgets[full])
  Using cached colorthief-0.2.1-py2.py3-none-any.whl (6.1 kB)
Collecting PyQt5-sip<13,>=12.11 (from PyQt5>=5.15.0->PyQt-Fluent-Widgets[full])
  Using cached PyQt5_sip-12.12.1-cp39-cp39-win_amd64.whl (78 kB)
Collecting PyQt5-Qt5>=5.15.2 (from PyQt5>=5.15.0->PyQt-Fluent-Widgets[full])
  Using cached PyQt5_Qt5-5.15.2-py3-none-win_amd64.whl (50.1 MB)
Collecting pywin32 (from PyQt5-Frameless-Window>=0.2.7->PyQt-Fluent-Widgets[full])
  Using cached pywin32-306-cp39-cp39-win_amd64.whl (9.3 MB)
Collecting numpy<1.28.0,>=1.21.6 (from scipy->PyQt-Fluent-Widgets[full])
  Obtaining dependency information for numpy<1.28.0,>=1.21.6 from https://files.pythonhosted.org/packages/86/c7/f92afdefa2bccdf0bc357321a931adafb1a999bc84f8877a6ed786a69ccc/numpy-1.25.1-cp39-cp39-win_amd64.whl.metadata
  Using cached numpy-1.25.1-cp39-cp39-win_amd64.whl.metadata (5.7 kB)
Using cached PyQt5_Frameless_Window-0.2.8-py3-none-any.whl (36 kB)
Using cached Pillow-10.0.0-cp39-cp39-win_amd64.whl (2.5 MB)
Using cached PyQt_Fluent_Widgets-1.0.2-py3-none-any.whl (1.6 MB)
Using cached scipy-1.11.1-cp39-cp39-win_amd64.whl (44.1 MB)
Using cached numpy-1.25.1-cp39-cp39-win_amd64.whl (15.1 MB)
Installing collected packages: pywin32, PyQt5-Qt5, PyQt5-sip, PyQt5-Frameless-Window, pillow, numpy, darkdetect, scipy, PyQt5, colorthief, PyQt-Fluent-Widgets
Successfully installed PyQt-Fluent-Widgets-1.0.2 PyQt5-5.15.9 PyQt5-Frameless-Window-0.2.8 PyQt5-Qt5-5.15.2 PyQt5-sip-12.12.1 colorthief-0.2.1 darkdetect-0.8.0 numpy-1.25.1 pillow-10.0.0 pywin32-306 scipy-1.11.1
```

</p>
</details> 

6. Clone repo

```
git clone https://github.com/zhiyiYo/PyQt-Fluent-Widgets.git
```

7. Checkout PyQt5 branch

```
cd PyQt-Fluent-Widgets
git checkout PyQt5
```

8. Launch designer

```
python ./tools/designer.py
```

I got the following error:

```
Traceback (most recent call last):
  File "D:\app\pyqt5\PyQt-Fluent-Widgets\tools\designer.py", line 72, in <module>
    designer.start(get_designer_path(), [])
  File "D:\app\pyqt5\PyQt-Fluent-Widgets\tools\designer.py", line 27, in get_designer_path
    raise Exception(
Exception: Can't find available QtDesigner for current environment. You can try `pip install pyqt5-tools` to solve this problem.
```
9. Install pyqt5-tools

```
pip install pyqt5-tools
```
10. Launch designer

```
python ./tools/designer.py
```

Output:

```
Copy D:\app\pyqt5\pyqt5\Lib\site-packages\pyqt5_plugins\Qt\plugins\designer\pyqt5.dll to D:\app\pyqt5\pyqt5\Lib\site-packages\qt5_applications\Qt\plugins\designer\pyqt5.dll.
```

## Screenshots

Screenshot 1:

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/111271571/baa5e75d-911f-4ac4-9052-fb3a1f28a091)

Screenshot 2:

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/111271571/e6100c9e-fc6f-48ea-b140-6176fe01608d)

I am unable to see the use PyQt-Fluent-Widgets in QtDesigner.

**Comment by zhiyiYo** [comment]
check #196
