### ISSUE TITLE
关于gallery的demo.py运行报错问题

### ISSUE THREAD

**Issue by cxjnevergiveup** [zhiyiYo/PyQt-Fluent-Widgets#376]
python：3.8.10
虚拟环境中

(venv) PS C:\Users\cxj\Desktop\PyQt-Fluent-Widgets-master\examples\gallery> python .\demo.py
Traceback (most recent call last):
  File "C:\Users\cxj\Desktop\PyQt-Fluent-Widgets-master\venv\lib\site-packages\qfluentwidgets\components\widgets\acrylic_label.py", line 33, in run 
    pixmap = gaussianBlur(
  File "C:\Users\cxj\Desktop\PyQt-Fluent-Widgets-master\venv\lib\site-packages\qfluentwidgets\common\image_utils.py", line 18, in gaussianBlur      
    image = Image.fromqpixmap(QPixmap(imagePath))
  File "C:\Users\cxj\Desktop\PyQt-Fluent-Widgets-master\venv\lib\site-packages\PIL\Image.py", line 3112, in fromqpixmap
    raise ImportError(msg)
ImportError: Qt bindings are not installed
(venv) PS C:\Users\cxj\Desktop\PyQt-Fluent-Widgets-master\examples\gallery> 
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/52702777/27e628fc-9507-418e-803e-3c902e6013be)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/52702777/b6549b25-4dee-4123-90b6-7ff2650bd0c0)

**Comment by zhiyiYo** [comment]
把 Pillow 版本降到 9.4.0

**Comment by cxjnevergiveup** [comment]
哇 可以了 谢谢 好牛

**Comment by zhiyiYo** [comment]
v1.4.6 已取消对 Pillow 版本的限制
