### ISSUE TITLE
AcrylicLabel在PySide6中出现异常。

### ISSUE THREAD

**Issue by tom9672** [zhiyiYo/PyQt-Fluent-Widgets#387]
当我使用PyQt-Fluent-Widgets的时候出现以下警告
```
(test_fluent_pyqt6) C:\Users\Administrator\Desktop\fluent_demo\examples\gallery>python demo.py
C:\Users\Administrator\.conda\envs\test_fluent_pyqt6\lib\site-packages\qfluentwidgets\components\widgets\acrylic_label.py:11: UserWarning: `AcrylicLabel` is not supported in current qfluentwidgets, use `pip install PyQt-Fluent-Widgets[full]` to enable it.
  warnings.warn(

```
当我使用PyQt-Fluent-Widgets[full]的时候出现以下报错
```
(test_fluent_pyqt6) C:\Users\Administrator\Desktop\fluent_demo>python .\examples\gallery\demo.py
Traceback (most recent call last):
  File "C:\Users\Administrator\.conda\envs\test_fluent_pyqt6\lib\site-packages\qfluentwidgets\components\widgets\acrylic_label.py", line 33, in run
    pixmap = gaussianBlur(
  File "C:\Users\Administrator\.conda\envs\test_fluent_pyqt6\lib\site-packages\qfluentwidgets\common\image_utils.py", line 18, in gaussianBlur
    image = Image.fromqpixmap(QPixmap(imagePath))
  File "C:\Users\Administrator\.conda\envs\test_fluent_pyqt6\lib\site-packages\PIL\Image.py", line 3113, in fromqpixmap
    return ImageQt.fromqpixmap(im)
  File "C:\Users\Administrator\.conda\envs\test_fluent_pyqt6\lib\site-packages\PIL\ImageQt.py", line 85, in fromqpixmap
    return fromqimage(im)
  File "C:\Users\Administrator\.conda\envs\test_fluent_pyqt6\lib\site-packages\PIL\ImageQt.py", line 74, in fromqimage
    im.save(buffer, "ppm")
TypeError: arguments did not match any overloaded call:
  save(self, fileName: str, format: typing.Optional[str] = None, quality: int = -1): argument 1 has unexpected type 'PySide6.QtCore.QBuffer'
  save(self, device: QIODevice, format: typing.Optional[str] = None, quality: int = -1): argument 1 has unexpected type 'PySide6.QtCore.QBuffer'
```

是因为acrylic_label和PySide6不兼容吗？

**Comment by zhiyiYo** [comment]
和 #376  重复了
