### ISSUE TITLE
gallery 运行不了

### ISSUE THREAD

**Issue by fromann** [zhiyiYo/PyQt-Fluent-Widgets#418]
**Describe the bug**
gallery 运行出错

**Environment**
环境信息
- OS: Windows10
- DPI scaling: 125%
- Python: 3.11
- PyQt: 5.15.2
- PyQt-Fluent-Widgets: latest

**To Reproduce**
1.cd gallery
2.python demo.py
3. See error

**Code**
python demo.py
```txt
(pyqt) E:\SunShine\Desktop>python PyQt-Fluent-Widgets\examples\gallery\demo.py
Traceback (most recent call last):
  File "D:\ESoftware\Environment\Conda\envs\pyqt\Lib\site-packages\qfluentwidgets\components\widgets\acrylic_label.py", line 33, in run
    pixmap = gaussianBlur(
             ^^^^^^^^^^^^^
  File "D:\ESoftware\Environment\Conda\envs\pyqt\Lib\site-packages\qfluentwidgets\common\image_utils.py", line 18, in gaussianBlur
    image = Image.fromqpixmap(QPixmap(imagePath))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ESoftware\Environment\Conda\envs\pyqt\Lib\site-packages\PIL\Image.py", line 3112, in fromqpixmap
    raise ImportError(msg)
ImportError: Qt bindings are not installed
```
**Screenshots**
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/54677852/296e78a5-cf7e-4de8-bdf6-94d867dfe1d6)

**Comment by zhiyiYo** [comment]
pillow版本换成9.4.0

**Comment by fromann** [comment]
#376
