### ISSUE TITLE
无法导入NavigationItemPostion，谁来救救我

### ISSUE THREAD

**Issue by LimeBow-Studios** [zhiyiYo/PyQt-Fluent-Widgets#420]
## 这是完整的日志。
----
# 安装
```
Microsoft Windows [版本 10.0.22621.1105]
(c) Microsoft Corporation。保留所有权利。

G:\PythonProjects\PyQt-Fluent-Widgets-master>python -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --upgrade pip
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pip in c:\users\limebow\appdata\local\programs\python\python310\lib\site-packages (22.3.1)
Collecting pip
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/50/c2/e06851e8cc28dcad7c155f4753da8833ac06a5c704c109313b8d5a62968a/pip-23.2.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.3.1
    Uninstalling pip-22.3.1:
      Successfully uninstalled pip-22.3.1
Successfully installed pip-23.2.1

G:\PythonProjects\PyQt-Fluent-Widgets-master>pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
Writing to C:\Users\LimeBow\AppData\Roaming\pip\pip.ini

G:\PythonProjects\PyQt-Fluent-Widgets-master>pip install "PyQt-Fluent-Widgets[full]"
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting PyQt-Fluent-Widgets[full]
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/19/f9/1c4c123b50aa8209f15ec84de8cd23707b03cbb89a4e62a58b9e20a9e80b/PyQt_Fluent_Widgets-1.0.4-py3-none-any.whl (1.6 MB)
Collecting PyQt5>=5.15.0 (from PyQt-Fluent-Widgets[full])
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/55/5d/8df8a2aa0de6588965d048fca9306cf15a5801be3078f195e8f8f41fa863/PyQt5-5.15.9-cp37-abi3-win_amd64.whl (6.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 844.0 kB/s eta 0:00:00
Collecting PyQt5-Frameless-Window>=0.2.7 (from PyQt-Fluent-Widgets[full])
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/42/bb/0e7e030d18ef3c9bc62431656377bfa6e8979e5ecadf5ca71715d45d97d2/PyQt5_Frameless_Window-0.3.0-py3-none-any.whl (36 kB)
Collecting darkdetect (from PyQt-Fluent-Widgets[full])
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f2/f2/728f041460f1b9739b85ee23b45fa5a505962ea11fd85bdbe2a02b021373/darkdetect-0.8.0-py3-none-any.whl (9.0 kB)
Collecting scipy (from PyQt-Fluent-Widgets[full])
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ce/e4/50b6fd4a2b65222424646abf17830904c9190bdd2c8daa7aeec083273903/scipy-1.11.1-cp310-cp310-win_amd64.whl (44.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 MB 583.8 kB/s eta 0:00:00
Collecting pillow (from PyQt-Fluent-Widgets[full])
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/d0/4f/faebe1180e5e6ad6330c539dda7f6081182157393ba6816a438f759a0e59/Pillow-10.0.0-cp310-cp310-win_amd64.whl (2.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 953.5 kB/s eta 0:00:00
Collecting colorthief (from PyQt-Fluent-Widgets[full])
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/56/18/be03b7058e65f9df479b14e7af4e73945ce311e07aaad45cf2536e14791a/colorthief-0.2.1-py2.py3-none-any.whl (6.1 kB)
Collecting PyQt5-sip<13,>=12.11 (from PyQt5>=5.15.0->PyQt-Fluent-Widgets[full])
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/9e/d1/2865085040c7bc553298553f51d6ac46b5051481b5c3eb8aad4bb5b63497/PyQt5_sip-12.12.2-cp310-cp310-win_amd64.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 545.1 kB/s eta 0:00:00
Collecting PyQt5-Qt5>=5.15.2 (from PyQt5>=5.15.0->PyQt-Fluent-Widgets[full])
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/37/97/5d3b222b924fa2ed4c2488925155cd0b03fd5d09ee1cfcf7c553c11c9f66/PyQt5_Qt5-5.15.2-py3-none-win_amd64.whl (50.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 613.7 kB/s eta 0:00:00
Collecting pywin32 (from PyQt5-Frameless-Window>=0.2.7->PyQt-Fluent-Widgets[full])
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/d3/d6/891894edec688e72c2e308b3243fad98b4066e1839fd2fe78f04129a9d31/pywin32-306-cp310-cp310-win_amd64.whl (9.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 933.3 kB/s eta 0:00:00
Collecting numpy<1.28.0,>=1.21.6 (from scipy->PyQt-Fluent-Widgets[full])
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/b7/db/4d37359e2c9cf8bf071c08b8a6f7374648a5ab2e76e2e22e3b808f81d507/numpy-1.25.2-cp310-cp310-win_amd64.whl (15.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.6/15.6 MB 886.2 kB/s eta 0:00:00
Installing collected packages: pywin32, PyQt5-Qt5, PyQt5-sip, PyQt5-Frameless-Window, pillow, numpy, darkdetect, scipy, PyQt5, colorthief, PyQt-Fluent-Widgets
Successfully installed PyQt-Fluent-Widgets-1.0.4 PyQt5-5.15.9 PyQt5-Frameless-Window-0.3.0 PyQt5-Qt5-5.15.2 PyQt5-sip-12.12.2 colorthief-0.2.1 darkdetect-0.8.0 numpy-1.25.2 pillow-10.0.0 pywin32-306 scipy-1.11.1
```
# 运行
```
G:\PythonProjects\PyQt-Fluent-Widgets-master>cd examples/gallery

G:\PythonProjects\PyQt-Fluent-Widgets-master\examples\gallery>python demo.py
Traceback (most recent call last):
  File "G:\PythonProjects\PyQt-Fluent-Widgets-master\examples\gallery\demo.py", line 9, in <module>
    from app.view.main_window import MainWindow
  File "G:\PythonProjects\PyQt-Fluent-Widgets-master\examples\gallery\app\view\main_window.py", line 7, in <module>
    from qfluentwidgets import (NavigationInterface, NavigationItemPostion, MessageBox,
ImportError: cannot import name 'NavigationItemPostion' from 'qfluentwidgets' (C:\Users\LimeBow\AppData\Local\Programs\Python\Python310\lib\site-packages\qfluentwidgets\__init__.py)
```
# 版本信息
```
G:\PythonProjects\PyQt-Fluent-Widgets-master\examples\gallery>python --version
Python 3.10.9
```
```
G:\PythonProjects\PyQt-Fluent-Widgets-master\examples\gallery>pip --version
pip 23.2.1 from C:\Users\LimeBow\AppData\Local\Programs\Python\Python310\lib\site-packages\pip (python 3.10)
```

**Comment by zhiyiYo** [comment]
现在版本都 1.0.4 了

**Comment by LimeBow-Studios** [comment]
看安装最后一行，就是1.0.4啊
`Successfully installed PyQt-Fluent-Widgets-1.0.4 ..`
