### ISSUE TITLE
ImportError: cannot import name 'NavigationItemPostion' from 'qfluentwidgets' 问题

### ISSUE THREAD

**Issue by LimeBow-Studios** [zhiyiYo/PyQt-Fluent-Widgets#435]
问题描述在：
无法导入NavigationItemPostion，谁来救救我 [#420](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/420)

**Comment by LimeBow-Studios** [comment]
# 回复 Owner：
看安装最后一行，就是1.0.4啊
`Successfully installed PyQt-Fluent-Widgets-1.0.4 ..`

**Comment by LimeBow-Studios** [comment]
# 回复 Owner：
昨天重装python还是不行
今天划分区重装了一次[官网](https://www.microsoft.com/ja-jp/software-download/windows11)下的ISO的win11还是不行
也写了将近1年的python小软件了
想试试NEW的方法
没想到前进的路这么坎坷
有可以解决的朋友回一下谢谢啦

**Comment by zhiyiYo** [comment]
NavigationItemPostion 是 0.7.0 之前的拼写错误，0.7.0 就改回来了

**Comment by LimeBow-Studios** [comment]
又有了船新错误，等下我上传下错误信息

**Comment by LimeBow-Studios** [comment]
```
Microsoft Windows [版本 10.0.22621.1105]
(c) Microsoft Corporation。保留所有权利。

G:\fuckPython\out\PyQt-Fluent-Widgets-master\examples\gallery>python demo.py
Traceback (most recent call last):
  File "G:\fuckPython\out\PyQt-Fluent-Widgets-master\examples\gallery\demo.py", line 11, in <module>
    from app.view.main_window import MainWindow
  File "G:\fuckPython\out\PyQt-Fluent-Widgets-master\examples\gallery\app\view\main_window.py", line 18, in <module>
    from .menu_interface import MenuInterface
  File "G:\fuckPython\out\PyQt-Fluent-Widgets-master\examples\gallery\app\view\menu_interface.py", line 5, in <module>
    from qfluentwidgets import (RoundMenu, PushButton, Action, CommandBar, Action, TransparentDropDownPushButton,
**ImportError: cannot import name 'AvatarWidget' from 'qfluentwidgets'** (C:\Users\LimeBow\AppData\Local\Programs\Python\Python310\lib\site-packages\qfluentwidgets\__init__.py)
```

**Comment by zhiyiYo** [comment]
现在已经升级到 1.1.3 了

**Comment by LimeBow-Studios** [comment]
# 已解决
启动成功了谢谢
话说更新也太快了吗（相对我来说）
