### ISSUE TITLE
SwitchButton出现TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by gamesun** [zhiyiYo/PyQt-Fluent-Widgets#477]
**Describe the bug**
SwitchButton在其checkedChanged事件中setChecked(not isChecked)时，出现多次TypeError: 'NoneType' object is not callable

**Environment**
环境信息
- OS: Windows10
- DPI scaling: 100%
- Python: 3.10.10 64-bit]
- PySide2: 5.15.2.1
- PySide2-Fluent-Widgets: 1.1.7

**To Reproduce**
运行最小代码，点击按钮即触发

**Code**
最小复现代码
```python
# coding:utf-8
import sys
from PySide2.QtCore import Qt
from PySide2.QtWidgets import QApplication, QWidget

from qfluentwidgets import SwitchButton


class Window(QWidget):

    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self.resize(160, 80)
        self.switchButton = SwitchButton(parent=self)
        self.switchButton.move(48, 24)
        self.switchButton.checkedChanged.connect(self.onCheckedChanged)

    def onCheckedChanged(self, isChecked: bool):
        self.switchButton.setChecked(not isChecked)
        # text = 'On' if isChecked else 'Off'
        # self.switchButton.setText(text)


if __name__ == '__main__':
    # enable dpi scale
    QApplication.setHighDpiScaleFactorRoundingPolicy(
        Qt.HighDpiScaleFactorRoundingPolicy.PassThrough)
    QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
    QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)

    app = QApplication(sys.argv)
    w = Window()
    w.show()
    sys.exit(app.exec_())

```

**Expected behavior**
取消点击事件，还原点击之前的isChecked状态

**Log**
...
...
TypeError: 'NoneType' object is not callable
TypeError: 'NoneType' object is not callable
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "E:\Python\Python310\lib\site-packages\qfluentwidgets\components\widgets\switch_button.py", line 229, in _updateText
    self.setText(self.onText if self.isChecked() else self.offText)
  File "E:\Python\Python310\lib\site-packages\qfluentwidgets\components\widgets\switch_button.py", line 217, in isChecked
    return self.indicator.isChecked()
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "e:\Projects\PyQt-Fluent-Widgets\examples\switch_button\demo.py", line 19, in onCheckedChanged
    self.switchButton.setChecked(not isChecked)
  File "E:\Python\Python310\lib\site-packages\qfluentwidgets\components\widgets\switch_button.py", line 221, in setChecked
    self._updateText()
RecursionError: maximum recursion depth exceeded while calling a Python object
TypeError: 'NoneType' object is not callable
TypeError: 'NoneType' object is not callable
...

**Comment by zhiyiYo** [comment]
你这样不就无线递归了吗😂

**Comment by gamesun** [comment]
使用场景是这样的，用户打开一个com口，但是这个com口被占用了，打开失败，提示用户失败，并且要把这个switch关掉

**Comment by zhiyiYo** [comment]
那也不能在 checkedChanged 的槽函数里面改呀

**Comment by gamesun** [comment]
我之前用的这个AnimationSwitchButton，可以在槽函数里面这么干

```python
# PySide2
from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import Qt, Signal, QPoint, QVariantAnimation, QRect
from PySide2.QtGui import QIcon, QPainter, QColor, QPen, QPainterPath, QRadialGradient
signal = Signal

# PyQt5
# from PyQt5 import QtCore, QtGui, QtWidgets
# from PyQt5.QtCore import Qt, pyqtSignal, QPoint, QVariantAnimation, QRect
# from PyQt5.QtGui import QIcon, QPainter, QColor, QPen, QPainterPath, QRadialGradient
# signal = pyqtSignal

buttonStyle_Rect = 0
buttonStyle_CircleIn = 1
buttonStyle_CircleOut = 2
        
class AnimationSwitchButton(QtWidgets.QToolButton):
    stateChanged = signal(bool)
    
    def __init__(self, parent = None):
        super(AnimationSwitchButton, self).__init__(parent)
        
        self.space = 2
        self.rectRadius = 12
        self.checked = False
        self.showText = False
        self.showCircle = False
        self.buttonStyle = buttonStyle_CircleIn

        self.bgColorOff = QColor('#6F7A7E')
        self.bgColorOn = QColor('#0072BB') #QColor('#22A3A9')
        self.sliderColorOff = QColor('#FEFEFE')
        self.sliderColorOn = QColor('#FEFEFE') #QColor('#22A3A9') 
        self.textColorOff = QColor('#f0f')
        self.textColorOn = QColor('#ff0')

        self.textOff = 'off'
        self.textOn = 'on'

        self.sliderX = None
        
        self.slider_animation = QVariantAnimation(self)
        self.slider_animation.setDuration(90)
        #self.slider_animation.setEasingCurve()
        self.slider_animation.valueChanged.connect(self.onSliderAnimationValueChanged)
        #self.slider_animation.stateChanged.connect(self.onSliderAnimationStateChanged)

    def setChecked(self, a0:bool):
        self.checked = a0
        if QVariantAnimation.Running == self.slider_animation.state():
            self.slider_animation.stop()
        self.slider_animation.setEndValue(0 if self.checked else (self.width() - self.height()))
        self.slider_animation.start()

    #def onSliderAnimationStateChanged(self, a, b):
    #    print('currentValue', self.slider_animation.currentValue())

    def onSliderAnimationValueChanged(self, value):
        if value != None:
            self.sliderX = value
            self.update()
    
    def mousePressEvent(self, mouseEvent):
        if mouseEvent.button() == Qt.LeftButton:
            self.checked = not self.checked
            self.slider_animation.setStartValue(self.sliderX)
            self.slider_animation.setEndValue(0 if self.checked else (self.width() - self.height()))
            self.slider_animation.start()
            self.stateChanged.emit(self.checked)
        mouseEvent.accept()

    def paintEvent(self, paintEvent):
        if None == self.sliderX:
            self.sliderX = 0 if self.checked else (self.width() - self.height())
        
        painter = QPainter(self)
        painter.setRenderHints(QPainter.Antialiasing | QPainter.TextAntialiasing)

        self.drawBg(painter)
        self.drawSlider(painter)

    def drawBg(self, painter):
        painter.save()
        painter.setPen(Qt.NoPen)

        bgColor = self.checked and self.bgColorOn or self.bgColorOff
        if not self.isEnabled():
            bgColor.setAlpha(60)

        painter.setBrush(bgColor)

        if self.buttonStyle == buttonStyle_Rect:
            painter.drawRoundedRect(self.rect(), self.rectRadius, self.rectRadius)
        elif self.buttonStyle == buttonStyle_CircleIn:
            rect = QRect(0, 0, self.width(), self.height())
            side = min(rect.width(), rect.height())

            path1 = QPainterPath()
            path1.addEllipse(rect.x(), rect.y(), side, side)
            path2 = QPainterPath()
            path2.addEllipse(rect.width() - side, rect.y(), side, side)
            path3 = QPainterPath()
            path3.addRect(rect.x() + side // 2, rect.y(), rect.width() - side, rect.height())

            path = QPainterPath()
            path = path3 + path1 + path2
            painter.drawPath(path)
        elif self.buttonStyle == buttonStyle_CircleOut:
            rect = QRect(self.height() // 2, self.space, self.width() - self.height(), self.height() - self.space * 2)
            painter.drawRoundedRect(rect, self.rectRadius, self.rectRadius)

        if self.buttonStyle == buttonStyle_Rect or self.buttonStyle == buttonStyle_CircleIn:
            if self.showText:
                sliderWidth = min(self.width(), self.height()) - self.space * 2
                if self.buttonStyle == buttonStyle_Rect:
                    sliderWidth = self.width() // 2 - 5
                elif self.buttonStyle == buttonStyle_CircleIn:
                    sliderWidth -= 5

                if self.checked:
                    textRect = QRect(0, 0, self.width() - sliderWidth, self.height())
                    painter.setPen(self.textColorOn)
                    painter.drawText(textRect, Qt.AlignCenter, self.textOn)
                else:
                    textRect = QRect(sliderWidth, 0, self.width() - sliderWidth, self.height())
                    painter.setPen(self.textColorOff)
                    painter.drawText(textRect, Qt.AlignCenter, self.textOff)
            elif self.showCircle:
                side = min(self.width(), self.height()) // 2
                y = (self.height() - side) // 2

                if self.checked:
                    circleRect = QRect(side // 2, y, side, side)
                    pen = QPen(self.textColorOn, 2)
                    painter.setPen(pen)
                    painter.setBrush(Qt.NoBrush)
                    painter.drawEllipse(circleRect)
                else:
                    circleRect = QRect(int(self.width() - (side * 1.5)), y, side, side)
                    pen = QPen(self.textColorOff, 2)
                    painter.setPen(pen)
                    painter.setBrush(Qt.NoBrush)
                    painter.drawEllipse(circleRect)

        painter.restore()

    def drawSlider(self, painter):
        painter.save()
        painter.setPen(Qt.NoPen)

        if not self.checked:
            painter.setBrush(self.sliderColorOff)
        else:
            painter.setBrush(self.sliderColorOn)

        if self.buttonStyle == buttonStyle_Rect:
            sliderWidth = self.width() // 2 - self.space * 2
            sliderHeight = self.height() - self.space * 2
            sliderRect = QRect(self.sliderX + self.space, self.space, sliderWidth , sliderHeight)
            painter.drawRoundedRect(sliderRect, self.rectRadius, self.rectRadius)
        elif self.buttonStyle == buttonStyle_CircleIn:
            rect = QRect(0, 0, self.width(), self.height())
            sliderWidth = min(rect.width(), rect.height()) - self.space * 2
            sliderRect = QRect(self.sliderX + self.space, self.space, sliderWidth, sliderWidth)
            painter.drawEllipse(sliderRect)
        elif self.buttonStyle == buttonStyle_CircleOut:
            sliderWidth = self.height()
            sliderRect = QRect(self.sliderX, 0, sliderWidth, sliderWidth)

            color1 = self.checked and Qt.white or self.bgColorOff
            color2 = self.checked and self.sliderColorOn or self.sliderColorOff

            radialGradient = QRadialGradient(sliderRect.center(), sliderWidth // 2)
            radialGradient.setColorAt(0, self.checked and color1 or color2)
            radialGradient.setColorAt(0.5, self.checked and color1 or color2)
            radialGradient.setColorAt(0.6, self.checked and color2 or color1)
            radialGradient.setColorAt(1.0, self.checked and color2 or color1)
            painter.setBrush(radialGradient)

            painter.drawEllipse(sliderRect)

        painter.restore()
```

**Comment by gamesun** [comment]
> 那也不能在 checkedChanged 的槽函数里面改呀

可以，我要用个timer延迟一会再改吗

**Comment by zhiyiYo** [comment]
就在提示失败的那个槽函数里面 setChecked(False) 就好了

**Comment by gamesun** [comment]
> 就在提示失败的那个槽函数里面 setChecked(False) 就好了

```python
    def onCheckedChanged(self, isChecked: bool):
        if isChecked:
            self.switchButton.setChecked(False)
```
对了，一开始就是这样写的，但是会有9次`TypeError: 'NoneType' object is not callable`
