### ISSUE TITLE
Flyout 出错

### ISSUE THREAD

**Issue by ShionCox** [zhiyiYo/PyQt-Fluent-Widgets#504]
**Describe the bug**
Flyout弹出一次后，再弹第二次就会保存，提示已删除，但是我打印测试是并没有删除的

**Environment**
环境信息
- OS: Windows11
- DPI scaling: 100%
- Python: 3.11.4
- PyQt: 5.15.9
- PyQt-Fluent-Widgets:1.2

**To Reproduce**
复现问题的步骤，推荐使用 gif 进行演示。
![动画](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/139309562/87a61e8f-6d33-41e3-8a0b-5d93eccc40ce)

**Code**
最小复现代码
```python

class Task_AvatarWidget(AvatarWidget):

    def __init__(self,
                 image: QPixmap,
                 parent=None,
                 name: str = "廖**",
                 phone: str = "18888888888",
                 email: str = "65464644@qq.com",
                 images: str = 'images/welcome/09.jpg'):
        super().__init__(parent)
        self.setImage(image)
        self.name = name
        self.phone = phone
        self.email = email
        self.images = images
        self._postInit()
        self.timer = QTimer(self)
        self.timer.timeout.connect(self.handleTimeout)
        self.user_info = FlyoutView(
            title=self.tr(name),
            content=self.tr(f"电话：{phone}\n邮箱：{email}"),
            image=images,
        )

    def enterEvent(self, event):
        self.timer.start(1000)

    def leaveEvent(self, event):
        self.timer.stop()

    def handleTimeout(self):
        print(self.user_info)
        Flyout.make(self.user_info, self, self.window(),
                    FlyoutAnimationType.SLIDE_RIGHT)
        self.timer.stop()


```

报错代码：
```
Traceback (most recent call last):
  File "F:\OneDrive\Python\Qnm\Program\Kit\task_info_step2.py", line 56, in handleTimeout
    Flyout.make(self.user_info, self, self.window(),
  File "i:\py\even\Lib\site-packages\qfluentwidgets\components\widgets\flyout.py", line 265, in make
    w = Flyout(view, parent, isDeleteOnClose)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "i:\py\even\Lib\site-packages\qfluentwidgets\components\widgets\flyout.py", line 213, in __init__
    self.hBoxLayout.addWidget(self.view)
RuntimeError: wrapped C/C++ object of type FlyoutView has been deleted
```

**Comment by zhiyiYo** [comment]
isDeleteOnClose 参数设置为 False 就行
