### ISSUE TITLE
窗口移动事件在wayland下无法正常工作

### ISSUE THREAD

**Issue by hiyms** [zhiyiYo/PyQt-Fluent-Widgets#527]
**Describe the bug**
在Wayland下运行主窗口类为`FluentWindows`的程序，移动创建的窗口，立刻出现如下错误后程序崩溃：
```
Traceback (most recent call last):
  File "/home/yms/.pyvenv/lib/python3.11/site-packages/qframelesswindow/titlebar/__init__.py", line 59, in mousePressEvent
    startSystemMove(self.window(), e.globalPos())
  File "/home/yms/.pyvenv/lib/python3.11/site-packages/qframelesswindow/utils/__init__.py", line 23, in startSystemMove
    MoveResize.startSystemMove(window, globalPos)
  File "/home/yms/.pyvenv/lib/python3.11/site-packages/qframelesswindow/utils/linux_utils.py", line 125, in startSystemMove
    cls.startSystemMoveResize(
  File "/home/yms/.pyvenv/lib/python3.11/site-packages/qframelesswindow/utils/linux_utils.py", line 87, in startSystemMoveResize
    cls.sendButtonReleaseEvent(window, globalPos)
  File "/home/yms/.pyvenv/lib/python3.11/site-packages/qframelesswindow/utils/linux_utils.py", line 52, in sendButtonReleaseEvent
    conn = xcb.wrap(sip.unwrapinstance(QX11Info.connection()))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unwrapinstance() argument 1 must be sip.simplewrapper, not None
```

**Environment**
- OS:  ArchLinux x86_64
- DPI scaling: 100%
- Python: 3.11.5 64-bit
- PyQt:  5.15.2
- PyQt-Fluent-Widgets:  1.2.2
- 显示服务器协议:  wayland

**To Reproduce**
1. 运行一个主窗口类为`FluentWindow`的程序
2. 尝试移动窗口
3. 报错

**代码**
```python
from PyQt5.QtWidgets import QApplication
import sys
from qfluentwidgets import FluentWindow
app = QApplication(sys.argv)
w = FluentWindow()
w.show()
app.exec()
```

**建议**
我发现`linux_utils.py`中定义的LinuxMoveResize类代码与xorg有较强关联，这很有可能是导致该错误的原因

**Comment by rainzee** [comment]
是跟 xorg 耦合导致的应该
