### ISSUE TITLE
设置语言报错QLocale 对象无法被 pickle 序列化

### ISSUE THREAD

**Issue by JFkirito** [zhiyiYo/PyQt-Fluent-Widgets#651]
### What happened?

PyQt 6.6.0 环境运行example中settings的demo时会报错

但是运行gallery时设置语言是正常的

### Operation System

Windows10

### Python Version

3.10.11

### PyQt/PySide Version

PyQt 6.6.0

### PyQt/PySide-Fluent-Widgets Version

1.3.2

### How to Reproduce?

以下是错误报告

Traceback (most recent call last):
  File "K:\Projects\ProjectYui\YuiVenv\lib\site-packages\qfluentwidgets\components\settings\setting_card.py", line 425, in _onCurrentIndexChanged
    qconfig.set(self.configItem, self.comboBox.itemData(index))
  File "K:\Projects\ProjectYui\YuiVenv\lib\site-packages\qfluentwidgets\common\config.py", line 298, in set
    item.value = deepcopy(value) if copy else value
  File "D:\ZexdProgram\Python3.10.11\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "D:\ZexdProgram\Python3.10.11\lib\copy.py", line 265, in _reconstruct
    y = func(*args)
  File "D:\ZexdProgram\Python3.10.11\lib\copy.py", line 264, in <genexpr>
    args = (deepcopy(arg, memo) for arg in args)
  File "D:\ZexdProgram\Python3.10.11\lib\copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'QLocale' object

### Minimum code

```python3
Pycharm运行demo
```

**Comment by zhiyiYo** [comment]
应该是 deepcopy 引起的，下个版本修复一下
