### ISSUE TITLE
安装时卡在了pip install pyqt5-tools.[Bug]: 

### ISSUE THREAD

**Issue by bigbigtooth** [zhiyiYo/PyQt-Fluent-Widgets#694]
### What happened?

执行pip install pyqt5-tools 时，卡着不懂，加入 --verbose看到系统提示如下：

 Successfully installed PyQt-builder-1.15.4 packaging-23.2 setuptools-69.0.3 sip-6.8.1 tomli-2.0.1
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Getting requirements to build wheel ... done
  Running command Preparing metadata (pyproject.toml)
  Querying qmake about your Qt installation...
  This is the GPL version of PyQt 5.15.9 (licensed under the GNU General Public License) for Python 3.8.18 on darwin.

  Type 'L' to view the license.
  Type 'yes' to accept the terms of the license.
  Type 'no' to decline the terms of the license.

提示要输入yes或者no确定这个license，试过很多方法都无法输入。

我的Qmake是v3.1

### Operation System

MacOS 14.2.1 (23C71)

### Python Version

3.8.18

### PyQt/PySide Version

pyqt5.15.9

### PyQt/PySide-Fluent-Widgets Version

1.4.5

### How to Reproduce?

执行pip install pyqt5-tools

### Minimum code

```python3
pip install pyqt5-tools --verbose
```

**Comment by zhiyiYo** [comment]
换成 pyqt6 吧，M 芯片好像用不了 pyqt5-tools

**Comment by bigbigtooth** [comment]
直接安装pyqt6-tools吗？我直接安装时失败的，报错也是类似的。能不能出一个教程呀？！

运行pip install pyqt6-tools报错信息：

  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Getting requirements to build wheel ... done
  Running command Preparing metadata (pyproject.toml)
  Querying qmake about your Qt installation...
  pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
  Traceback (most recent call last):
    File "/Users/davidwu/anaconda3/envs/LiveroomAssistant/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/Users/davidwu/anaconda3/envs/LiveroomAssistant/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/davidwu/anaconda3/envs/LiveroomAssistant/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
      whl_basename = backend.build_wheel(metadata_directory, config_settings)
    File "/private/var/folders/vs/t8pyxcvj5mxfpvqsk7j0kf8h0000gn/T/pip-build-env-lblf32c7/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 46, in build_wheel
      project = AbstractProject.bootstrap('wheel',
    File "/private/var/folders/vs/t8pyxcvj5mxfpvqsk7j0kf8h0000gn/T/pip-build-env-lblf32c7/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
      project.setup(pyproject, tool, tool_description)
    File "/private/var/folders/vs/t8pyxcvj5mxfpvqsk7j0kf8h0000gn/T/pip-build-env-lblf32c7/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 603, in setup
      self.update(tool)
    File "project.py", line 157, in update
  sipbuild.exceptions.UserException
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

**Comment by zhiyiYo** [comment]
再不行就换成 PySide6
