### ISSUE TITLE
[Bug]: Pro组件的颜色选择器以及快捷键选择器点击重置按钮在QtPy版本报错

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#724]
### What happened?

错误日志：
颜色选择器点击弹出窗口点击查看更多颜色按钮报错
`Traceback (most recent call last):
  File "qfluentwidgetspro/components/widgets/slider.py", line 269, in qfluentwidgetspro.components.widgets.slider.ColorSlider._adjustHandlePos
TypeError: _adjustHandlePos() takes exactly 1 positional argument (2 given)`

`Traceback (most recent call last):
  File "qfluentwidgetspro/components/widgets/color_palette.py", line 407, in qfluentwidgetspro.components.widgets.color_palette.ColorPaletteView._onMoreColorClicked
TypeError: _onMoreColorClicked() takes exactly 1 positional argument (2 given)`

快捷键选择器点击重置按钮报错：
`Traceback (most recent call last):
  File "qfluentwidgetspro/components/widgets/shortcut_picker.py", line 156, in qfluentwidgetspro.components.widgets.shortcut_picker.ShortcutDialog._onResetButtonClicked
TypeError: _onResetButtonClicked() takes exactly 1 positional argument (2 given)`

### Operation System

Mac

### Python Version

3.11.7

### PyQt/PySide Version

PyQt 5.15.9

### PyQt/PySide-Fluent-Widgets Version

v1.4.6

### How to Reproduce?

PySide6版本正常

### Minimum code

```python3
demo文件
```

**Comment by zhiyiYo** [comment]
编译成 pyd 之后槽函数也不能缺少位置参数了，难崩
