### ISSUE TITLE
[Bug]: Pro组件中的日期范围选择器在QtPy版本第二次点击日期范围选择器时崩溃

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#732]
### What happened?

QtPy版本的日期范围选择器点击后选择日期范围，选择完成后再次点击按钮时无法打开日期范围选择器，出现崩溃
崩溃日志
`Traceback (most recent call last):
  File "/Users/test/Library/pypoetry/virtualenvs/my-fluentwidgets-pro-RETBMcfS-py3.11/lib/python3.11/site-packages/qfluentwidgets/components/date_time/calendar_view.py", line 71, in paint
    self._drawBackground(painter, option, index)
  File "qfluentwidgetspro/components/date_time/calendar_picker.py", line 294, in qfluentwidgetspro.components.date_time.calendar_picker.RangeDayScrollItemDelegate._drawBackground
TypeError: arguments did not match any overloaded call:
  addEllipse(self, rect: QRectF): argument 1 has unexpected type 'QRect'
  addEllipse(self, x: float, y: float, w: float, h: float): argument 1 has unexpected type 'QRect'
  addEllipse(self, center: Union[QPointF, QPoint], rx: float, ry: float): argument 1 has unexpected type 'QRect'`

### Operation System

Mac

### Python Version

3.11.7

### PyQt/PySide Version

PyQt 5.15.9

### PyQt/PySide-Fluent-Widgets Version

v1.4.6

### How to Reproduce?

PySide版本正常

### Minimum code

```python3
demo文件
```

**Comment by LxHTT** [comment]
这个看着像把QRect当QRectF用了

**Comment by zhiyiYo** [comment]
已修复此问题
