### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'qframelesswindow'

### ISSUE THREAD

**Issue by NeonBubbles** [zhiyiYo/PyQt-Fluent-Widgets#736]
### What happened?

我按照官网操安装pip install "PyQt6-Fluent-Widgets[full]" -i https://pypi.org/simple/
然后克隆仓库代码，切换到PyQT6分支，在终端中使用
cd examples/gallery
python demo.py

依然提示ModuleNotFoundError: No module named 'qframelesswindow'

Traceback (most recent call last):
  File "D:\PyQt-Fluent-Widgets\examples\gallery\demo.py", line 8, in <module>
    from qfluentwidgets import FluentTranslator
  File "C:\Users\clank\AppData\Roaming\Python\Python39\site-packages\qfluentwidgets\__init__.py", line 18, in <module>
    from .components import *
  File "C:\Users\clank\AppData\Roaming\Python\Python39\site-packages\qfluentwidgets\components\__init__.py", line 1, in <module>
    from .dialog_box import *
  File "C:\Users\clank\AppData\Roaming\Python\Python39\site-packages\qfluentwidgets\components\dialog_box\__init__.py", line 1, in <module>
    from .color_dialog import ColorDialog
  File "C:\Users\clank\AppData\Roaming\Python\Python39\site-packages\qfluentwidgets\components\dialog_box\color_dialog.py", line 8, in <module>
    from ..widgets import ClickableSlider, SingleDirectionScrollArea, PushButton, PrimaryPushButton
  File "C:\Users\clank\AppData\Roaming\Python\Python39\site-packages\qfluentwidgets\components\widgets\__init__.py", line 1, in <module>
    from .button import (DropDownPushButton, DropDownToolButton, PrimaryPushButton, PushButton, RadioButton,
  File "C:\Users\clank\AppData\Roaming\Python\Python39\site-packages\qfluentwidgets\components\widgets\button.py", line 14, in <module>
    from .menu import RoundMenu, MenuAnimationType
  File "C:\Users\clank\AppData\Roaming\Python\Python39\site-packages\qfluentwidgets\components\widgets\menu.py", line 5, in <module>
    from qframelesswindow import WindowEffect
ModuleNotFoundError: No module named 'qframelesswindow'
<img width="444" alt="20240126003937511" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/43613294/72648598-32ae-44fe-9b69-c797390c3228">

### Operation System

windows 11 21H2

### Python Version

3.9.16

### PyQt/PySide Version

PyQT6  6.6.1

### PyQt/PySide-Fluent-Widgets Version

 1.4.6

### How to Reproduce?

.

### Minimum code

```python3
.
```

**Comment by zhiyiYo** [comment]
搞个新环境看看
