### ISSUE TITLE
[Bug]: MessageBoxBase 无法在缺少父组件的情况下运行

### ISSUE THREAD

**Issue by Zhikun0201** [zhiyiYo/PyQt-Fluent-Widgets#894]
### What happened?

Traceback (most recent call last):
  File "D:\Projects\NarratinPySide\scripts\widgets\dialog\_dialog.py", line 22, in <module>
    dialog = Dialog()
             ^^^^^^^^
  File "D:\Projects\NarratinPySide\scripts\widgets\dialog\_dialog.py", line 6, in __init__
    super(Dialog, self).__init__(parent)
  File "D:\Projects\NarratinPySide\venv\Lib\site-packages\qfluentwidgets\components\dialog_box\message_box_base.py", line 19, in __init__
    super().__init__(parent=parent)
  File "D:\Projects\NarratinPySide\venv\Lib\site-packages\qfluentwidgets\components\dialog_box\mask_dialog_base.py", line 22, in __init__
    self.setGeometry(0, 0, parent.width(), parent.height())
                           ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'width'

### Operation System

Windows 11 23H2

### Python Version

3.12

### PyQt/PySide Version

PySide6 6.7.1

### PyQt/PySide-Fluent-Widgets Version

v1.5.7

### How to Reproduce?

运行Code

### Minimum code

```python3
if __name__ == '__main__':
    from PySide6.QtWidgets import QApplication
    import sys

    app = QApplication(sys.argv)
    dialog = MessageBoxBase()
    dialog.show()
    sys.exit(app.exec_())
```

**Comment by zhiyiYo** [comment]
必须有父级
