### ISSUE TITLE
建议增加支持python3.11及以上版本

### ISSUE THREAD

**Issue by monkeycc** [zhiyiYo/PyQt-Fluent-Widgets#933]
建议增加支持python3.11及以上版本

3.11
3.12

**Comment by zhiyiYo** [comment]
本来就支持吧？什么地方报错了吗

**Comment by monkeycc** [comment]
```python
pip install "PySide6-Fluent-Widgets[full]" -i https://pypi.org/simple/
cd examples/gallery
python demo.py

---------------------------------
Traceback (most recent call last):
  File "signature_bootstrap.py", line 77, in bootstrap
  File "signature_bootstrap.py", line 93, in find_incarnated_files
  File "D:\anaconda3\envs\py311\Lib\pathlib.py", line 871, in __new__
    self = cls._from_parts(args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\py311\Lib\pathlib.py", line 509, in _from_parts
    drv, root, parts = self._parse_args(args)
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\py311\Lib\pathlib.py", line 493, in _parse_args
    a = os.fspath(a)
        ^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
Fatal Python error: could not initialize part 2
Python runtime state: initialized

Current thread 0x00003ff4 (most recent call first):
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1233 in create_module
  File "<frozen importlib._bootstrap>", line 573 in module_from_spec
  File "<frozen importlib._bootstrap>", line 676 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1147 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1176 in _find_and_load
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1232 in _handle_fromlist
  File "D:\anaconda3\envs\py311\Lib\site-packages\PySide6\__init__.py", line 64 in _setupQtDirectories
  File "D:\anaconda3\envs\py311\Lib\site-packages\PySide6\__init__.py", line 124 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 940 in exec_module
  File "<frozen importlib._bootstrap>", line 690 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1147 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1176 in _find_and_load
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1126 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1176 in _find_and_load
  File "D:\anaconda3\envs\py311\Lib\site-packages\qfluentwidgets\components\dialog_box\color_dialog.py", line 2 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 940 in exec_module
  File "<frozen importlib._bootstrap>", line 690 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1147 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1176 in _find_and_load
  File "D:\anaconda3\envs\py311\Lib\site-packages\qfluentwidgets\components\dialog_box\__init__.py", line 1 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 940 in exec_module
  File "<frozen importlib._bootstrap>", line 690 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1147 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1176 in _find_and_load
  File "D:\anaconda3\envs\py311\Lib\site-packages\qfluentwidgets\components\__init__.py", line 1 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 940 in exec_module
  File "<frozen importlib._bootstrap>", line 690 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1147 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1176 in _find_and_load
  File "D:\anaconda3\envs\py311\Lib\site-packages\qfluentwidgets\__init__.py", line 18 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 940 in exec_module
  File "<frozen importlib._bootstrap>", line 690 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1147 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1176 in _find_and_load
  File "E:\2023_Code_WEB\PyQt-Fluent-Widgets-master\examples\gallery\demo.py", line 8 in <module>

Extension modules: PyQt5.QtCore, PyQt5.QtGui, PyQt5.QtWidgets, xxsubtype, shiboken6.Shiboken (total: 5)
```

**Comment by monkeycc** [comment]
用个虚拟机
win11
用最新版本anaconda
创建一个python3.11环境

这样是否能复现

1.判断anacond环境是否有问题
2.判断系统环境是否有问题

**Comment by zhiyiYo** [comment]
你搞个新的虚拟环境试试吧，这个明显不是组件库的报错

**Comment by rainzee** [comment]
> 用个虚拟机 win11 用最新版本anaconda 创建一个python3.11环境
> 
> 这样是否能复现
> 
> 1.判断anacond环境是否有问题 2.判断系统环境是否有问题

我开发和排错组件库都是在3.11上的，一定不会有问题，是你那边的问题
