### ISSUE TITLE
[Bug]: SegmentedWidget call clear() causes an error.

### ISSUE THREAD

**Issue by Sug2077** [zhiyiYo/PyQt-Fluent-Widgets#975]
### What happened?

Calling the clear() method causes an error

```shell
Traceback (most recent call last):
  File "D:\Github\PyQt-Fluent-Widgets\qfluentwidgets\components\navigation\pivot.py", line 238, in resizeEvent
    self._adjustIndicatorPos()
  File "D:\Github\PyQt-Fluent-Widgets\qfluentwidgets\components\navigation\pivot.py", line 241, in _adjustIndicatorPos
    item = self.currentItem()
           ^^^^^^^^^^^^^^^^^^
  File "D:\Github\PyQt-Fluent-Widgets\qfluentwidgets\components\navigation\pivot.py", line 185, in currentItem
    return self.widget(self._currentRouteKey)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Github\PyQt-Fluent-Widgets\qfluentwidgets\components\navigation\pivot.py", line 232, in widget
    raise RouteKeyError(f"`{routeKey}` is illegal.")
qfluentwidgets.components.navigation.navigation_panel.RouteKeyError: `songInterface` is illegal.
```

### Operation System

Windows 10 22H2

### Python Version

3.11.9 64bit

### PyQt/PySide Version

Pyside6 6.7.2

### PyQt/PySide-Fluent-Widgets Version

1.6.5

### How to Reproduce?

see Minimum code

### Minimum code

```python3
# coding:utf-8
import sys

from PySide6.QtCore import Qt
from PySide6.QtWidgets import QApplication, QWidget, QStackedWidget, QVBoxLayout, QLabel

from qfluentwidgets import SegmentedWidget, PushButton


class Demo(QWidget):

    def __init__(self):
        super().__init__()
        # setTheme(Theme.DARK)
        self.setStyleSheet("""
            Demo{background: white}
            QLabel{
                font: 20px 'Segoe UI';
                background: rgb(242,242,242);
                border-radius: 8px;
            }
        """)
        self.resize(400, 400)

        self.pivot = SegmentedWidget(self)
        self.stackedWidget = QStackedWidget(self)
        self.vBoxLayout = QVBoxLayout(self)

        self.songInterface = QLabel('Song Interface', self)
        self.albumInterface = QLabel('Album Interface', self)
        self.artistInterface = QLabel('Artist Interface', self)

        # add items to pivot
        self.addSubInterface(self.songInterface, 'songInterface', 'Song')
        self.addSubInterface(self.albumInterface, 'albumInterface', 'Album')
        self.addSubInterface(self.artistInterface, 'artistInterface', 'Artist')

        self.vBoxLayout.addWidget(self.pivot)
        self.vBoxLayout.addWidget(self.stackedWidget)
        self.vBoxLayout.setContentsMargins(30, 10, 30, 30)

        self.stackedWidget.setCurrentWidget(self.songInterface)
        self.pivot.setCurrentItem(self.songInterface.objectName())
        self.pivot.currentItemChanged.connect(
            lambda k: self.stackedWidget.setCurrentWidget(self.findChild(QWidget, k)))

        # test_code
        self.btn = PushButton('清空pivot测试', self)
        self.vBoxLayout.addWidget(self.btn)
        self.btn.clicked.connect(self.pivot.clear)

    def addSubInterface(self, widget: QLabel, objectName, text):
        widget.setObjectName(objectName)
        widget.setAlignment(Qt.AlignCenter)
        self.stackedWidget.addWidget(widget)
        self.pivot.addItem(routeKey=objectName, text=text)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    w = Demo()
    w.show()
    app.exec()
```

**Comment by AlexZhu2001** [comment]
Finished
